Name = "local"
Level = "Debug"
TokenExpiry = "168h0m0s"
Port = 1789
Host = "127.0.0.1"

[API.GRPC]
Retries = 5
Hosts = [
    "localhost:3007",
]

[API.REST]
Hosts = [
    "localhost:3009"
]

[API.GraphQL]
Hosts = [
    "localhost:3008"
]


