Name = "local"
Level = "info"
TokenExpiry = "168h0m0s"
Port = 1789
Host = "0.0.0.0"

[API]
  [API.GRPC]
    Hosts = ["datanode:3007"]
    Retries = 5
  [API.REST]
    Hosts = ["datanode:3009"]
  [API.GraphQL]
    Hosts = ["datanode:3008"]

[Console]
  URL = ""
  LocalPort = 0

[Nodes]
  Retries = 0
